version: '3'

services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: onlinesalesdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
